---
# tasks file for roles/hardening

# ── Firewall────────────────────────────────────
- name: Ensure firewalld is running and enabled
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: Allow required services through firewall
  ansible.posix.firewalld:
    zone: '{{ hardening_firewall_zone }}'
    service: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  loop: '{{ hardening_firewall_services_allowed }}' 
  notify: Reload firewalld

- name: Remove disallowed services from firewall
  ansible.posix.firewalld:
    zone: '{{ hardening_firewall_zone }}'
    service: '{{ item }}'
    permanent: true
    immediate: true
    state: disabled
  loop: '{{ hardening_firewall_services_blocked }}'
  notify: Reload firewalld

# ── SELinux─────────────────────────────────────
- name: Set SELinux mode
  ansible.posix.selinux:
    state: '{{ hardening_selinux_state }}' 
    policy: '{{ hardening_selinux_policy }}'
  register: selinux_result

- name: Reboot if SELinux mode changed
  ansible.builtin.reboot:
     msg: 'Rebooting to apply SELinux mode change'
     reboot_timeout: 300
  when: selinux_result.reboot_required | default(false)

- name: Set SELinux booleans
  ansible.posix.seboolean:
    name: '{{ item.name }}'  
    state: '{{ item.state }}'
    persistent: true
  loop: '{{ hardening_selinux_booleans }}'

# ── fail2ban─────────────────────────────────────
- name: Import EPEL 9 GPG key
  ansible.builtin.rpm_key:
    key: '{{ hardening_epel_gpg_key }}'
    state: present

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: '{{ hardening_epel_rpm }}' 
    state: present

- name: Update cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install Fail2ban
  ansible.builtin.dnf:
    name: '{{ hardening_packages }}'
    state: present


- name: Deploy fail2ban jail configuration
  ansible.builtin.template:
    src: hardening.conf.j2
    dest: '{{ hardening_fail2ban_jail_config }}'
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true  
