---
# vars file for roles/hardening
hardening_packages:
  hardening_epel_rpm: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  hardening_epel_gpg_key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
  - fail2ban
  - fail2ban-firewalld
hardening_fail2ban_jail_config: /etc/fail2ban/jail.d/hardening.conf

